export enum PrayerPraise {
  PRAYER = 'PRAYER',
  PRAISE = 'PRAISE'
}

export enum ShareStatus {
  SHARED_WITH_EVERYONE = 'SHARED_WITH_EVERYONE',
  SHARED_WITH_NOONE = 'SHARED_WITH_NOONE',
  SHARED_WITH_PRAYER_TEAM = 'SHARED_WITH_PRAYER_TEAM'
}
