export const FETCH_MY_MESSAGES          = 'app/MY_DATA/FETCH_MY_MESSAGES';
export const FETCH_MY_MESSAGES_FAILED   = 'app/MY_DATA/FETCH_MY_MESSAGES_FAILED';
export const FETCH_MY_MESSAGES_INFLIGHT = 'app/MY_DATA/FETCH_MY_MESSAGES_INFLIGHT';
export const FETCH_MY_MESSAGES_SUCCESS  = 'app/MY_DATA/FETCH_MY_MESSAGES_SUCCESS';

export const DELETE_MESSAGE          = 'app/MY_DATA/DELETE_MESSAGE';
export const DELETE_MESSAGE_FAILED   = 'app/MY_DATA/DELETE_MESSAGE_FAILED';
export const DELETE_MESSAGE_INFLIGHT = 'app/MY_DATA/DELETE_MESSAGE_INFLIGHT';
export const DELETE_MESSAGE_SUCCESS  = 'app/MY_DATA/DELETE_MESSAGE_SUCCESS';

export const SET_MESSAGE_TO_EDIT     = 'app/MY_DATA/SET_MESSAGE_TO_EDIT';

export const EDIT_MESSAGE            = 'app/MY_DATA/EDIT_MESSAGE';
export const EDIT_MESSAGE_FAILED     = 'app/MY_DATA/EDIT_MESSAGE_FAILED';
export const EDIT_MESSAGE_INFLIGHT   = 'app/MY_DATA/EDIT_MESSAGE_INFLIGHT';
export const EDIT_MESSAGE_SUCCESS    = 'app/MY_DATA/EDIT_MESSAGE_SUCCESS';

export const UPDATE_MESSAGE          = 'app/MY_DATA/UPDATE_MESSAGE';
export const UPDATE_MESSAGE_FAILED   = 'app/MY_DATA/UPDATE_MESSAGE_FAILED';
export const UPDATE_MESSAGE_INFLIGHT = 'app/MY_DATA/UPDATE_MESSAGE_INFLIGHT';
export const UPDATE_MESSAGE_SUCCESS  = 'app/MY_DATA/UPDATE_MESSAGE_SUCCESS';

export const CHANGE_EXISTING_MESSAGE_SHARED_STATUS = 'app/MY_DATA/CHANGE_EXISTING_MESSAGE_SHARED_STATUS';
export const CHANGE_EXISTING_MESSAGE_TEXT = 'app/MY_DATA/CHANGE_EXISTING_MESSAGE_TEXT';
